apiVersion: v1
kind: Secret
metadata:
    name: ahmed-mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= #echo -n dXNlcm5hbWU= | base64 --decode --> username
    mongo-root-password: cGFzc3dvcmQ= #echo -n cGFzc3dvcmQ= | base64 --decode --> password

